---
apiVersion: v1
data:
  CACHEURL: http://192.168.222.100/images
  DEPLOY_KERNEL_URL: http://192.168.222.100:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://192.168.222.100:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 192.168.222.100,192.168.222.200
  HTTP_PORT: "6180"
  IRONIC_FAST_TRACK: "true"
  IRONIC_KERNEL_PARAMS: console=ttyS0
  LISTEN_ALL_INTERFACES: '"false"'
  PROVISIONING_CIDR: "24"
  PROVISIONING_INTERFACE: ironicendpoint
  PROVISIONING_IP: 192.168.222.100
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "true"
  NUMWORKERS: "20"
  IRONIC_ENDPOINT: https://192.168.222.100:6385/v1/
  IRONIC_LISTEN_PORT: "6385"
  IRONIC_RAMDISK_SSH_KEY: {{ .Values.sshKey }}
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic-bmo-configmap
  namespace: {{ .Values.global.namespace }}
