---
apiVersion: v1
data:
  auth-config: |
    {{ .Values.secrets.ironicAuthConfig | b64enc }}
kind: Secret
metadata:
  name: baremetal-operator-ironic-auth-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  IRONIC_HTPASSWD: |
    {{ .Values.secrets.ironicHtpasswd | b64enc }}
kind: Secret
metadata:
  name: baremetal-operator-ironic-htpasswd
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: baremetal-operator-mariadb-password
  namespace: {{ .Values.global.namespace }}
type: Opaque
