apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: test1
  namespace: test2
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/18
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: test1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: Metal3Cluster
    name: test1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: Metal3Cluster
metadata:
  name: test1
  namespace: test2
spec:
  controlPlaneEndpoint:
    host: 192.168.111.250
    port: 6443
  noCloudProvider: true
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: provisioning-pool
  namespace: test2
spec:
  clusterName: test1
  namePrefix: test1-prov
  pools:
  - end: 172.23.0.200
    start: 172.23.0.100
  prefix: 24
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: baremetalv4-pool
  namespace: test2
spec:
  clusterName: test1
  gateway: 192.168.111.2
  namePrefix: test1-bmv4
  pools:
  - end: 192.168.111.248
    start: 192.168.111.201
  prefix: 24
