apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- my-cluster.yaml
- ippool.yaml

patches:
- path: patch.yaml
  target:
    kind: Metal3DataTemplate
    name: my-cluster-controlplane-template
