apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: my-cluster-controlplane-template
spec:
  clusterName: my-cluster
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: enp1s0
    networks:
      ipv4:
        - id: kcpv4
          link: enp1s0
          ipAddressFromIPPool: kcp
          routes:
            - network: 0.0.0.0
              prefix: 0
              gateway:
                fromIPPool: kcp
    services:
      dns:
        - 8.8.8.8
