---
apiVersion: v1
data:
  auth-config: |
    W2lyb25pY10KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9SjI1MlV1SU5KSkduCn
    Bhc3N3b3JkPVJtcXlacW16Z3NNRg==
kind: Secret
metadata:
  name: baremetal-operator-ironic-auth-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  IRONIC_HTPASSWD: |
    SjI1MlV1SU5KSkduOiQyeSQwNSRRd0dVb1d0RGcxektWTDdEcjFUUU5PMC5KbGUzUG01WD
    JRTnlnRWtLVnpSRG5HS1BEdkRqZQ==
kind: Secret
metadata:
  name: baremetal-operator-ironic-htpasswd
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  auth-config: |
    W2luc3BlY3Rvcl0KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9SjI1MlV1SU5KSk
    duCnBhc3N3b3JkPVJtcXlacW16Z3NNRg==
kind: Secret
metadata:
  name: baremetal-operator-ironic-inspector-auth-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  INSPECTOR_HTPASSWD: |
    SjI1MlV1SU5KSkduOiQyeSQwNSRlVEREbks4Rk9KN3JUZnNZSDBLTkt1dWcvYmJKLnhuT2
    xUTGhtOG5YeUd2RFo2NjRkUkVabQ==
kind: Secret
metadata:
  name: baremetal-operator-ironic-inspector-htpasswd
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: baremetal-operator-mariadb-password
  namespace: {{ .Values.global.namespace }}
type: Opaque
