global:
  ironicInspectorBaseUrl: "https://172.22.0.2:5050"
  namespace: baremetal-operator-system
  ironicNodeLockedRetryInterval: "2"
  ironicNodeLockedRetryAttempts: "15"
sshKey: <fill-me>
ironicReplicas: []
