# Reference: https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml
# TODO: Fix line length issues later

config:
  ul-indent:
    # Kramdown wanted us to have 3 earlier, tho this CLI recommends 2 or 4
    indent: 3
  line-length: false

# Don't autofix anything, we're linting here
fix: false
