yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  trailing-spaces: enable
  key-duplicates: enable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on']

# Ignore template files from helm chart
ignore:
- Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/**/*.yaml
