---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cni
  namespace: default
spec:
  strategy: "Reconcile"
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
    - name: calico
      kind: ConfigMap
