apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cni-crs.yaml
generatorOptions:
  disableNameSuffixHash: true

configmapGenerator:
- files:
  - calico.yaml
  name: calico
  namespace: default
