apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../ironic-bootstrap

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
  behavior: replace

patches:
- path: ironic-patch.yaml
# The TLS component adds certificates but it cannot know the exact IPs of our environment.
# Here we patch the certificates to have the correct IPs.
# - 192.168.222.1: management computer IP, forwarded to ironic inside kind
- patch: |-
    - op: replace
      path: /spec/ipAddresses/0
      value: 192.168.222.100
  target:
    kind: Certificate
    name: ironic-cert
