# we make it serve in nodeport 31389
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openldap
  name: openldap
  namespace: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
    spec:
      containers:
      - image: bitnami/openldap:latest
        name: openldap
        env:
        - name: LDAP_ADMIN_USERNAME
          value: admin
        - name: LDAP_ADMIN_PASSWORD
          value: adminpassword
        - name: LDAP_USERS
          value: customuser,foo
        - name: LDAP_PASSWORDS
          value: custompassword,bar
        - name: LDAP_ROOT
          value: dc=example,dc=org
        - name: LDAP_ADMIN_DN
          value: cn=admin,dc=example,dc=org
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
spec:
  type: NodePort
  ports:
  - name: openldap
    port: 1389
    protocol: TCP
    targetPort: 1389
    nodePort: 31389
  selector:
    app: openldap
