apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy
resources:
  - namespace.yaml
  - deployment.yaml

configMapGenerator:
  - name: haproxy-cfg
    files:
      - haproxy.cfg
