apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: baremetal-operator-leader-election-role
  namespace: test1
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: baremetal-operator-manager-role
  namespace: test1
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal3.io
  resources:
  - bmceventsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - bmceventsubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal3.io
  resources:
  - firmwareschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - firmwareschemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal3.io
  resources:
  - hardware/finalizers
  verbs:
  - update
- apiGroups:
  - metal3.io
  resources:
  - hardwaredata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - hostfirmwaresettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - hostfirmwaresettings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages/status
  verbs:
  - get
  - patch
  - update
