apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
namePrefix: baremetal-operator-
resources:
- ../../base
- namespace.yaml

components:
- ../../components/basic-auth
- ../../components/tls

secretGenerator:
  - name: ironic-credentials
    literals:
    - username=admin
    - password=password
  - name: ironic-inspector-credentials
    literals:
    - username=inspector
    - password=password

configMapGenerator:
- name: ironic
  behavior: create
  envs:
  - ironic.env
