---
apiVersion: v1
kind: Secret
metadata:
  name: node-2-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: node-2
spec:
  online: true
  bootMACAddress: 00:5c:52:31:3a:ad
  bootMode: legacy
  bmc:
    address: ipmi://192.168.111.1:6231
    credentialsName: node-2-bmc-secret
