---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baremetal-operator-leader-election-rolebinding
  namespace: test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baremetal-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: baremetal-operator-controller-manager
  namespace: test2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baremetal-operator-manager-rolebinding
  namespace: test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baremetal-operator-manager-role
subjects:
- kind: ServiceAccount
  name: baremetal-operator-controller-manager
  namespace: baremetal-operator-system-test2
