apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    app: manager
spec:
  containers:
    - image: quay.io/metal3-io/api-server:latest
      imagePullPolicy: IfNotPresent
      name: capim
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Always
