apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    app: manager
spec:
  containers:
    - image: 172.22.0.1:5000/localimages/capim
      imagePullPolicy: Always
      name: capim
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Always
