apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-baremetal
  name: capm3-serving-cert
  namespace: capm3-system-test1
spec:
  dnsNames:
  - capm3-webhook-service.capm3-system-test1.svc
  - capm3-webhook-service.capm3-system-test1.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capm3-selfsigned-issuer
  secretName: capm3-webhook-service-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-baremetal
  name: capm3-selfsigned-issuer
  namespace: capm3-system-test1
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-serving-cert
  namespace: capm3-system-test1
spec:
  dnsNames:
  - ipam-webhook-service.capm3-system-test1.svc
  - ipam-webhook-service.capm3-system-test1.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ipam-selfsigned-issuer
  secretName: ipam-webhook-service-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-selfsigned-issuer
  namespace: capm3-system-test1
spec:
  selfSigned: {}
