apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: baremetal-operator-system
---
apiVersion: v1
data:
  CACHEURL: http://172.22.0.1/images
  DEPLOY_KERNEL_URL: http://172.22.0.2:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://172.22.0.2:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 172.22.0.10,172.22.0.100
  HTTP_PORT: "6180"
  INSPECTOR_REVERSE_PROXY_SETUP: "false"
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_ENDPOINT: https://172.22.0.2:5050/v1/
  IRONIC_KERNEL_PARAMS: console=ttyS0
  LISTEN_ALL_INTERFACES: '"false"'
  PROVISIONING_CIDR: "24"
  PROVISIONING_INTERFACE: ironicendpoint
  PROVISIONING_IP: 172.22.0.2
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "true"
  NUMWORKERS: "20"
  IRONIC_ENDPOINT: https://172.22.0.2:6385/v1/
  IRONIC_LISTEN_PORT: "6385"
  IRONIC_RAMDISK_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5kcPprzNn8UEtOauwb5+wqWqAjy6ZFzAaf1ipeo11kGSpDwuyYCuNhVLAzUy07OsKaG/2PVDJ4p8EMVtWT+8jSI1gnF499Z/v8AahLEWzbxP3d/1aaiEIn7bxSq/CI0jtYPHydzAobCNz/DuP0+rGBtk5mY27rxpMRdLZ68que7uyJPbgi3VWyevHio7MgFbYYZhGmcboWUYQxMwkrDXZsIVqh2oiseBO0a0WCYPVkgi8PdXGPEAy490TFMP28u6f6gVvwWHy7QdqX+iBVSoDCYhPtVpfQd/nQJh9VEwk/lFLvGKUYYka+5Eade9rtI8yxiwKM38ZNuJc4MuLw8uFx+9skJDdWWgXF9q1pWREIuRz1lUE4p8l/JqkUv85G4854FC1TSQMQ1/oehd5hiBNGIxGm36euD316tJ8qZcCs1GSVbcqlchoqJtZmXCpSqgtnGR4LUrChsWG2aPX5gWvnaP/84R02pdivTNtXldqwtVZjYniW4RR4WZETs5wSMk=
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic-bmo-configmap
  namespace: baremetal-operator-system
---
apiVersion: v1
data:
  auth-config: |
    W2lyb25pY10KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9SjI1MlV1SU5KSkduCn
    Bhc3N3b3JkPVJtcXlacW16Z3NNRg==
kind: Secret
metadata:
  name: baremetal-operator-ironic-auth-config
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: v1
data:
  IRONIC_HTPASSWD: |
    SjI1MlV1SU5KSkduOiQyeSQwNSRRd0dVb1d0RGcxektWTDdEcjFUUU5PMC5KbGUzUG01WD
    JRTnlnRWtLVnpSRG5HS1BEdkRqZQ==
kind: Secret
metadata:
  name: baremetal-operator-ironic-htpasswd
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: v1
data:
  auth-config: |
    W2luc3BlY3Rvcl0KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9SjI1MlV1SU5KSk
    duCnBhc3N3b3JkPVJtcXlacW16Z3NNRg==
kind: Secret
metadata:
  name: baremetal-operator-ironic-inspector-auth-config
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: v1
data:
  INSPECTOR_HTPASSWD: |
    SjI1MlV1SU5KSkduOiQyeSQwNSRlVEREbks4Rk9KN3JUZnNZSDBLTkt1dWcvYmJKLnhuT2
    xUTGhtOG5YeUd2RFo2NjRkUkVabQ==
kind: Secret
metadata:
  name: baremetal-operator-ironic-inspector-htpasswd
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: baremetal-operator-mariadb-password
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic
  namespace: baremetal-operator-system
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      name: ironic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ironic
    spec:
      containers:
      - env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password
        - name: RESTART_CONTAINER_CERTIFICATE_UPDATED
          valueFrom:
            configMapKeyRef:
              key: RESTART_CONTAINER_CERTIFICATE_UPDATED
              name: baremetal-operator-ironic-bmo-configmap
        image: 172.22.0.1:5000/localimages/mariadb:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin status -uironic -p$(printenv MARIADB_PASSWORD)
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: mariadb
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin status -uironic -p$(printenv MARIADB_PASSWORD)
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 27
          runAsUser: 27
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
        - mountPath: /certs/mariadb
          name: cert-mariadb
          readOnly: true
        - mountPath: /certs/ca/mariadb
          name: cert-mariadb-ca
          readOnly: true
      - envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        image: 172.22.0.1:5000/localimages/keepalived:v0.2.0
        name: ironic-endpoint-keepalived
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-dnsmasq
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /auth/ironic-inspector
          name: ironic-inspector-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ironic-inspector
          name: cert-ironic-inspector
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /certs/ca/ironic-inspector
          name: cert-ironic-inspector-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic
        env:
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
        - name: INSPECTOR_REVERSE_PROXY_SETUP
          value: "true"
        - name: IRONIC_USE_MARIADB
          value: "true"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        - secretRef:
            name: baremetal-operator-ironic-htpasswd
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic
        volumeMounts:
        - mountPath: /certs/ca/mariadb
          name: cert-mariadb-ca
          readOnly: true
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /auth/ironic-inspector
          name: ironic-inspector-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ironic-inspector
          name: cert-ironic-inspector
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /certs/ca/ironic-inspector
          name: cert-ironic-inspector-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runlogwatch.sh
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-log-watch
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /auth/ironic-inspector
          name: ironic-inspector-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ironic-inspector
          name: cert-ironic-inspector
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /certs/ca/ironic-inspector
          name: cert-ironic-inspector-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic-inspector
        env:
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
        - name: INSPECTOR_REVERSE_PROXY_SETUP
          value: "true"
        envFrom:
        - secretRef:
            name: baremetal-operator-ironic-inspector-htpasswd
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-inspector
        volumeMounts:
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /certs/ca/ironic-inspector
          name: cert-ironic-inspector-ca
          readOnly: true
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        env:
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
        - name: INSPECTOR_REVERSE_PROXY_SETUP
          value: "true"
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-httpd
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /auth/ironic-inspector
          name: ironic-inspector-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ironic-inspector
          name: cert-ironic-inspector
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /certs/ca/ironic-inspector
          name: cert-ironic-inspector-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      hostNetwork: true
      initContainers:
      - command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        image: 172.22.0.1:5000/localimages/ironic-ipa-downloader
        imagePullPolicy: Always
        name: ironic-ipa-downloader
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      volumes:
      - name: cert-mariadb
        secret:
          secretName: mariadb-cert
      - name: cert-mariadb-ca
        secret:
          secretName: ironic-cacert
      - name: ironic-auth-config
        secret:
          secretName: baremetal-operator-ironic-auth-config
      - name: ironic-inspector-auth-config
        secret:
          secretName: baremetal-operator-ironic-inspector-auth-config
      - name: cert-ironic-ca
        secret:
          secretName: ironic-cacert
      - name: cert-ironic-inspector-ca
        secret:
          secretName: ironic-cacert
      - name: cert-ironic
        secret:
          secretName: ironic-cert
      - name: cert-ironic-inspector
        secret:
          secretName: ironic-inspector-cert
      - emptyDir: {}
        name: ironic-data-volume
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-ironic-cacert
  namespace: baremetal-operator-system
spec:
  commonName: ironic-ca
  ipAddresses:
  - 172.22.0.2
  isCA: true
  issuerRef:
    kind: Issuer
    name: baremetal-operator-selfsigned-issuer
  secretName: ironic-cacert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-ironic-cert
  namespace: baremetal-operator-system
spec:
  commonName: ironic-cert
  ipAddresses:
  - 172.22.0.2
  issuerRef:
    kind: Issuer
    name: baremetal-operator-ca-issuer
  secretName: ironic-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-ironic-inspector-cert
  namespace: baremetal-operator-system
spec:
  commonName: ironic-inspector-cert
  ipAddresses:
  - 172.22.0.2
  issuerRef:
    kind: Issuer
    name: baremetal-operator-ca-issuer
  secretName: ironic-inspector-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-mariadb-cert
  namespace: baremetal-operator-system
spec:
  commonName: mariadb-cert
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    kind: Issuer
    name: baremetal-operator-ca-issuer
  secretName: mariadb-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: baremetal-operator-ca-issuer
  namespace: baremetal-operator-system
spec:
  ca:
    secretName: ironic-cacert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: baremetal-operator-selfsigned-issuer
  namespace: baremetal-operator-system
spec:
  selfSigned: {}
