apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: baremetal-operator-system
---
apiVersion: v1
data:
  CACHEURL: http://172.22.0.1/images
  DEPLOY_KERNEL_URL: http://172.22.0.2:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://172.22.0.2:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 172.22.0.10,172.22.0.100
  HTTP_PORT: "6180"
  INSPECTOR_REVERSE_PROXY_SETUP: "false"
  IRONIC_ENDPOINT: http://172.22.0.2:6385/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_ENDPOINT: http://172.22.0.2:5050/v1/
  IRONIC_KERNEL_PARAMS: console=ttyS0
  LISTEN_ALL_INTERFACES: '"false"'
  PROVISIONING_CIDR: "24"
  PROVISIONING_INTERFACE: ironicendpoint
  PROVISIONING_IP: 172.22.0.2
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
  namespace: baremetal-operator-system
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: baremetal-operator-mariadb-password-ftkgc8tmkc
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic
  namespace: baremetal-operator-system
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      name: ironic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ironic
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/keepalived
        name: ironic-endpoint-keepalived
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-dnsmasq
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password-ftkgc8tmkc
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runlogwatch.sh
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-log-watch
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic-inspector
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-inspector
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/ironic
        imagePullPolicy: Always
        name: ironic-httpd
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      hostNetwork: true
      initContainers:
      - command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: 172.22.0.1:5000/localimages/ironic-ipa-downloader
        imagePullPolicy: Always
        name: ironic-ipa-downloader
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      volumes:
      - emptyDir: {}
        name: ironic-data-volume
