apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
spec:
  template:
    spec:
      containers:
        - name: ironic-dnsmasq
          $patch: delete
      volumes:
        - name: ironic-data-volume
          emptyDir:
            $patch: delete
          hostPath:
            path: /opt/minikube
