apiVersion: v1
kind: Namespace
metadata:
  name: vbmc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vbmc
  name: vbmc
  namespace: vbmc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vbmc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vbmc
    spec:
      hostNetwork: true
      containers:
      - image: quay.io/metal3-io/vbmc
        name: vbmc
        volumeMounts:
          - name: ssh
            mountPath: /home/docker/.ssh
      volumes:
        - name: ssh
          hostPath:
            path: /home/docker/.ssh
