{{- range $index, $ipValue := $.Values.ironicReplicas }}
---
apiVersion: v1
data:
  IRONIC_REVERSE_PROXY_SETUP: "true"
  IRONIC_USE_MARIADB: "true"
  PROVISIONING_IP: {{ $ipValue }}
  IRONIC_EXPOSE_JSON_RPC: "true"
  # IRONIC_EXPOSE_OSLO_RPC: "true"
  IRONIC_RAMDISK_HEARTBEAT_TIMEOUT: "3000"
  IRONIC_RPC_RESPONSE_TIMEOUT: "600"
  IRONIC_ENDPOINT: https://{{ $ipValue }}:6385/v1/
  OS_AGENT__REQUIRE_TLS: "false"
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic-{{ $index }}-configmap
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic-{{ $index }}
  namespace: {{ $.Values.global.namespace }}
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      name: ironic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ironic
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - command:
        - /bin/runironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        - configMapRef:
            name: baremetal-operator-ironic-{{ $index }}-configmap
        - secretRef:
            name: baremetal-operator-ironic-htpasswd
        image: quay.io/metal3-io/ironic:v26.0.1
        imagePullPolicy: IfNotPresent
        name: ironic
        volumeMounts:
        - mountPath: /certs/ca/mariadb
          name: cert-mariadb-ca
          readOnly: true
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runlogwatch.sh
        image: quay.io/metal3-io/ironic:v26.0.1
        imagePullPolicy: IfNotPresent
        name: ironic-log-watch
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap
        - configMapRef:
            name: baremetal-operator-ironic-{{ $index }}-configmap
        image: quay.io/metal3-io/ironic:v26.0.1
        imagePullPolicy: IfNotPresent
        name: ironic-httpd
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
        - mountPath: /certs/ironic
          name: cert-ironic
          readOnly: true
        - mountPath: /certs/ca/ironic
          name: cert-ironic-ca
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      hostNetwork: true
      # This was removed thanks to a hack in hostPath. Needs reconsideration if taken to
      # production.
      # initContainers:
      # - command:
      #   - touch /shared/ironic-python-agent.kernel /shared/ironic-python-agent.initramfs
      #   envFrom:
      #   - configMapRef:
      #       name: baremetal-operator-ironic-bmo-configmap
      #   image: ubuntu
      #   imagePullPolicy: Always
      #   name: fake-ironic-ipa-downloader
      #   volumeMounts:
      #   - mountPath: /shared
      #     name: ironic-data-volume
      volumes:
      - name: cert-mariadb
        secret:
          secretName: mariadb-cert
      - name: cert-mariadb-ca
        secret:
          secretName: ironic-cacert
      - name: ironic-auth-config
        secret:
          secretName: baremetal-operator-ironic-auth-config
      - name: cert-ironic-ca
        secret:
          secretName: ironic-cacert
      - name: cert-ironic
        secret:
          secretName: ironic-cert
      - name: ironic-data-volume
        hostPath:
          path: /shared
          type: Directory
{{- end }}
