apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: kamaji-1
spec:
  dataStoreName: default
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - ExternalIP
    - InternalIP
    - Hostname
  addons:
    coreDNS: {}
    kubeProxy: {}
  network:
    serviceType: LoadBalancer
    serviceAnnotations:
      metallb.io/loadBalancerIPs: "192.168.222.150"
  deployment:
  replicas: 2
  version: 1.33.0
