apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: md-kamaji-1
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: kamaji-1
spec:
  clusterName: kamaji-1
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kamaji-1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: kamaji-1
    spec:
      nodeDrainTimeout: "0s"
      clusterName: kamaji-1
      version: v1.33.0
      bootstrap:
        configRef:
          name: kamaji-1-workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: kamaji-1-workers
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
