# -*- mode: ruby -*-

hosts = {
    "control-plane1" => { "memory" => 2048, "ip" => "192.168.10.10"},
    # "worker1" => { "memory" => 2048, "ip" => "192.168.10.30"},
    # "worker2" => { "memory" => 2048, "ip" => "192.168.10.31"},
}

Vagrant.configure("2") do |config|
    # Choose which box you want below
    # config.vm.box = "generic/centos8"
    config.vm.box = "generic/ubuntu2004"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
      # QEMU system connection is required for private network configuration
      libvirt.qemu_use_session = false
    end

    # Loop over all machine names
    hosts.each_key do |host|
        config.vm.define host, primary: host == hosts.keys.first do |node|
            # Use custom box if set
            if hosts[host]["box"]
                node.vm.box = hosts[host]["box"]
            end

            node.vm.hostname = host
            node.vm.network :private_network, ip: hosts[host]["ip"],
              libvirt__forward_mode: "route"

            node.vm.provider :libvirt do |lv|
                lv.memory = hosts[host]["memory"]
                lv.cpus = 2
            end

            node.vm.provider :virtualbox do |vbox|
                vbox.customize ["modifyvm", :id, "--memory", hosts[host]["memory"]]
                vbox.cpus = 2
            end

        end
    end

end
