apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vcluster
  namespace: vcluster
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vcluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster
  namespace: vcluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: vcluster-k8s
      repo: null
      version: 0.10.1
    values: |
      sync:
        nodes:
          enableScheduler: true
      scheduler:
        disabled: false
      syncer:
        disabled: true
  kubernetesVersion: 1.23.0
