apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/config/overlays/basic-auth_tls?ref=release-0.5  

configMapGenerator:
- name: ironic
  behavior: create
  envs:
  - ironic.env

patches:
- patch: |
    # Don't try to pull again the pre-loaded image
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
    name: controller-manager

images:
- name: quay.io/metal3-io/baremetal-operator
  newTag: release-0.5

# We cannot use suffix hashes since the kustomizations we build on
# cannot be aware of what suffixes we add.
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ironic-credentials
    files:
    - username=ironic-username
    - password=ironic-password
  - name: ironic-inspector-credentials
    files:
    - username=ironic-username
    - password=ironic-password
